prSections:
- title: PR Open (k8s-platform)
  filters: is:open repo:FIL-Enterprise-Prod/TAPP200073_k8s-platform
- title: PR Closed (k8s-platform)
  filters: is:closed repo:FIL-Enterprise-Prod/TAPP200073_k8s-platform
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Involved
  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  issues: []
  prs:
    - key: C
      command: >
        tmux split-window -h -c {{.RepoPath}} '
          cd {{.RepoPath}} &&
          nvim {{.PrNumber}} -c ":bd" -c ":Octo pr edit {{.PrNumber}}"
        '
repoPaths:
  FIL-Enterprise-Prod/*: ~/development/FIL-Enterprise-Prod/*
theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#E2E1ED"
      secondary: "#666CA6"
      inverted: "#242347"
      faint: "#3E4057"
      warning: "#F23D5C"
      success: "#3DF294"
    background:
      selected: "#39386B"
    border:
      primary: "#383B5B"
      secondary: "#39386B"
      faint: "#2B2B40"
pager:
  diff: bat
